version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10.24.1
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run deploy-aws